# NumPy

NumPy to biblioteka do algebry liniowej w Pythonie, która odgrywa kluczową rolę w Data Science. Większość narzędzi w ekosystemie PyData opiera się na NumPy jako jednej z podstawowych technologii. Jest także bardzo szybka, ponieważ korzysta z bibliotek napisanych w C.

My poznamy tylko podstawy tej biblioteki.

------------------


## Używanie NumPy

W Colabie NumPy jest już zainstalowane, ale w innych środowiskach może być konieczne jej zainstalowanie.

Aby zainstalować NumPy w Pythonie (jeśli nie jest jeszcze zainstalowane), wystarczy użyć poniższej komendy w terminalu lub w notatniku:

```
!pip install numpy
```

Po zainstalowaniu możesz zaimportować NumPy do swojego projektu:

In [ ]:
import numpy as np

NumPy posiada wiele wbudowanych funkcji i możliwości. Nie omówimy ich wszystkich, ale skupimy się na najważniejszych aspektach NumPy. Zacznijmy od omówienia tablic.

# Numpy Arrays

Tablice NumPy (NumPy arrays) to struktury danych, które umożliwiają przechowywanie i manipulowanie dużymi zestawami danych w Pythonie. Są one bardziej wydajne niż standardowe listy Pythona i oferują szereg funkcji do łatwego wykonywania operacji matematycznych oraz obliczeń na dużych zbiorach danych.

## Tworzenie NumPy Arrays

### Z listy

Możemy stworzyć tablicę, bezpośrednio konwertując listę lub listę list:

In [ ]:
my_array = np.array([1, 2, 3, 4])
my_array

array([1, 2, 3, 4])

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # lista list
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Wbudowane metody

Istnieje wiele wbudowanych sposobów generowania tablic w NumPy.

### arange

Zwraca równomiernie rozmieszczone wartości w określonym przedziale.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2) # tu określasz wielkość kroku

array([ 0,  2,  4,  6,  8, 10])

### zeros i ones

Generuje tablice wypełnione zerami lub jedynkami.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Zwraca równomiernie rozmieszczoną określoną liczbę liczb w zadanym przedziale.

In [ ]:
np.linspace(0,10,3)  # tu okreslasz ile tych liczb ma być

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Tworzy macierz jednostkową.

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

NumPy oferuje również wiele sposobów generowania tablic z losowymi liczbami

### rand
tworzy tablicę o podanym kształcie i wypełnij ją
losowymi próbkami z rozkładu równomiernego
na `[0, 1)`.

In [ ]:
np.random.rand(5)

array([0.0977971 , 0.74576418, 0.51972047, 0.97216204, 0.57554294])

In [ ]:
np.random.rand(5,5)

array([[0.56310224, 0.00769378, 0.65335032, 0.91907388, 0.17824565],
       [0.66283866, 0.52204567, 0.01091442, 0.40339112, 0.18310881],
       [0.84111536, 0.44171351, 0.76919683, 0.01666108, 0.11769987],
       [0.11961647, 0.39676976, 0.9190561 , 0.08830029, 0.6751988 ],
       [0.89007344, 0.08918286, 0.14977624, 0.84893818, 0.10528574]])

### randn

Zwraca próbkę (lub próbki) z rozkładu "standardowego normalnego".

In [ ]:
np.random.randn(2)

array([-0.4675873 ,  1.11072183])

In [ ]:
np.random.randn(3,5)  # 3 - wiersze, 5 kolumn

array([[ 1.04063384, -1.2963603 ,  0.64788371, -0.04036143,  1.88977482],
       [-0.75647213,  1.40254733, -0.91222754, -1.6627943 ,  0.89247596],
       [-0.43208192, -1.05089161, -2.42338366, -0.90707271, -1.81193699]])

### randint
Zwraca losowe liczby całkowite z przedziału od `low` (włącznie) do `high` (wyłącznie).

In [ ]:
np.random.randint(1,100,1)


array([28])

In [ ]:
np.random.randint(1,100,10) #10 losowych liczb całkowitych w przedziale od 1 (włącznie) do 100 (wyłącznie)

array([13, 30, 82, 82, 20, 51, 19, 75, 67, 64])

## Atrybuty i metody Array

Omówmy kilka przydatnych atrybutów i metod dla tablic w NumPy.

Mamy dwie tablice: arr i ranarr

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([49,  2, 44, 10, 46, 32, 31, 11, 17,  7])

## Reshape
Zwraca tablicę zawierającą te same dane, ale o nowym kształcie.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### max,min,argmax,argmin

Przydatne metody do znajdowania maksymalnych lub minimalnych wartości. Można również znaleźć ich indeksy za pomocą `argmin` lub `argmax`

In [ ]:
ranarr

array([49,  2, 44, 10, 46, 32, 31, 11, 17,  7])

In [ ]:
ranarr.max()

np.int64(49)

In [ ]:
ranarr.max().item() # zwykła liczba

49

In [ ]:
ranarr.argmax() #index

np.int64(0)

In [ ]:
ranarr.min()

np.int64(2)

In [ ]:
ranarr.argmin()

np.int64(1)

## Shape

shape jest **atrybutem**, który posiada każda tablica w NumPy (a nie metodą). Zwraca on kształt tablicy, czyli liczbę elementów w każdym wymiarze tablicy:

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Vector
arr.shape # czyli jest to tablica 1D z 25 elementami.

(25,)

In [ ]:
# Teraz tablica będzie miała jeden wiersz i 25 kolumn, co daje (nawiasy []):
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape # Tablica ma teraz kształt (1, 25), czyli jest to tablica 2D z jednym wierszem i 25 kolumnami.

(1, 25)

In [ ]:
arr.reshape(25,1) #tablica będzie miała 25 wierszy i 1 kolumnę

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### dtype

Możesz również pobrać typ danych obiektu w tablicy:

In [ ]:
arr.dtype

dtype('int64')

### ndim
Możemy też sprawdzić wymiar tablicy

In [ ]:
arr.ndim

1

-------------


# NumPy - indeksowanie i wybieranie elementów z tablicy

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Najprostszy sposób na wybranie jednego lub kilku elementów tablicy wygląda bardzo podobnie do list Pythona:

In [ ]:
# Uzyskaj wartość z danego indeksu - !!! indeksujemy od 0
arr[8]

np.int64(8)

In [ ]:
ranarr

array([49,  2, 44, 10, 46, 32, 31, 11, 17,  7])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Uzyskaj wartości w przedziale (od 1 (włacznie) do 5 (wyłącznie))
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

## Broadcasting

Broadcasting to mechanizm NumPy, który pozwala na wykonywanie operacji arytmetycznych na tablicach o różnych wymiarach bez konieczności ich ręcznego dopasowywania.


In [ ]:
#Pojedyncza wartość może być rozszerzona (rozprowadzona) na wiele elementów tablicy bez konieczności używania pętli
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [ ]:
# Zresetujmy tablicę.
arr = np.arange(0,25)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#Uwagi dotyczące wycinków
slice_of_arr = arr[0:6]

#Slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Zmiana wycinka
slice_of_arr[:]=99

#Slice
slice_of_arr

array([99, 99, 99, 99, 99, 99])

A teraz wyświetlmy oryginalną tablicę

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Zauważcie, że zmiany zachodzą również oryginalnej tablicy!

- to nie jest kopia, tylko "widok" na oryginalną tablicę
- dzięki temu oszczędzamy pamięć, ponieważ nie duplikujemy danych

In [ ]:
#Aby uzyskać kopię, należy to zrobić jawnie.
arr_copy = arr[0:5].copy()

arr_copy[:]=100
print(arr_copy)
arr

[100 100 100 100 100]


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Indeksowanie tablicy 2D (macierzy)

Ogólny format to **arr_2d[row,col]**

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indeksowanie wiersza
arr_2d[1]


array([20, 25, 30])

In [ ]:
arr_2d[1,:]

array([20, 25, 30])

In [ ]:
# Pobieranie wartości pojedynczego elementu
# Format is arr_2d[row][col]
arr_2d[1][0]

np.int64(20)

In [ ]:
# Pobieranie wartości pojedynczego elementu
# Format arr_2d[row,col]
arr_2d[1,0]

np.int64(20)

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# Pobieranie fragmentów) z 2D tablicy NumPy

#Kształt (2,2) z prawego górnego rogu
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[:2][1:] # -> dlaczego nie to samo co arr_2d[:2,1:]?
# arr_2d[:2] → wybiera pierwsze dwa wiersze
# [1:] → teraz na tej nowej tablicy wybierasz wiersze od indeksu 1

array([[20, 25, 30]])

In [ ]:
#Kształt (2,2) z prawego górnego rogu
arr_2d[:2,1:]


array([[10, 15],
       [25, 30]])

In [ ]:
#Dolny rząd
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Dolny rząd
arr_2d[2,:]

array([35, 40, 45])

### Zaawansowane indeksowanie

Zaawansowane indeksowanie pozwala na wybieranie całych wierszy lub kolumn w dowolnej kolejności. Aby to pokazać, zbudujmy szybko tablicę NumPy:

In [ ]:
#Zbuujmy tablicę - na razie 0
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#Długość wiersza tablicy
arr_length = arr2d.shape[1]
arr_length

10

In [ ]:
# Uzupełnienie tablicy

for i in range(arr_length):
    arr2d[i] = i #cały wiersz

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Zaawansowane indeksowanie

In [ ]:
arr2d[[2,4,6,8]] # konkretne wiersze - indeks całego wiersza

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
# W odwrotnej kolejności też
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Wybór elementów z tablicy c.d.

Omówmy krótko, jak używać nawiasów do wyboru elementów na podstawie operatorów porównania.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Operacje NumPy

## Arytmetyka

Możesz łatwo wykonywać operacje arytmetyczne między tablicami lub między skalarem a tablicą (Broadcasting c..d.). Zobaczmy kilka przykładów:

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Ostrzeżenie o dzieleniu przez zero, ale nie błąd!
# Wartości zostały po prostu zastąpione nan.
arr/arr

<ipython-input-83-ce1c406b336e>:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Również ostrzeżenie, ale nie błąd – zamiast tego wartość nieskończoności (inf).
1/arr

<ipython-input-84-96c6c3634ffb>:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Uniwersalne funkcje tablicowe

NumPy zawiera wiele [uniwersalnych funkcji](https://numpy.org/doc/stable/reference/ufuncs.html) tablicowych, które są w zasadzie operacjami matematycznymi wykonywanymi na całej tablicy. Przeanalizujmy kilka najczęściej używanych:

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Obliczanie pierwiastków kwadratowych
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
#Obliczanie funkcji wykładniczej (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.max(arr) #to samo co arr.max()
arr.max(axis=0)

np.int64(9)

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

<ipython-input-94-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.sum(axis=1)

array([ 30,  75, 120])

Na dzisiaj tyle 👍