# NumPy Ćwiczenia

#### Import NumPy jako np

In [ ]:
import numpy as np

#### Utwórz tablicę 10 zer

Rezultat:

```
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```






In [ ]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Utwórz tablicę 10 jedynek

Rezultat:

```
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
```



In [ ]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Utwórz tablicę 10 piątek


Rezultat:
```
array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])
```



In [ ]:
a = np.ones(10)
a * 5.

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Utwórz tablicę liczb całkowitych od 10 do 50.

Rezultat:


```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])
```



In [ ]:
a = np.arange(10, 51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Utwórz tablicę wszystkich liczb całkowitych parzystych od 10 do 50.
Rezultat:


```
array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])
```



In [ ]:
a = np.arange(10, 51, 2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Utwórz macierz 3x3 z wartościami od 0 do 8.
Rezultat:

```
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```



In [ ]:
a = np.arange(9)
a.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Utwórz macierz jednostkową 3x3

Rezultat:


```
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```



In [ ]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Użyj NumPy, aby wygenerować losową liczbę z przedziału od 0 do 1

In [ ]:
a = np.random.randint(0,1)
a

0

#### Użyj NumPy, aby wygenerować tablicę 25 losowych liczb pobranych z standardowego rozkładu normalnego.

In [ ]:
a = np.random.rand(25)
a

array([0.92943927, 0.30150357, 0.01206395, 0.54079115, 0.15750197,
       0.24473562, 0.47816583, 0.7904226 , 0.82308721, 0.89436365,
       0.48780588, 0.9111054 , 0.00346498, 0.90808786, 0.75584362,
       0.73299309, 0.81515579, 0.50827302, 0.55669462, 0.11327406,
       0.53999639, 0.81508199, 0.03443369, 0.34986927, 0.43093658])

#### Utwórz następującą macierz:

```
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```



In [ ]:
a = np.arange(0.01, 1.01, 0.01)
a.reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Utwórz tablicę 20 równomiernie rozmieszczonych punktów między 0 a 1.

Rezultat:

```
rray([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])
```



In [ ]:
a = np.linspace(0, 1, 20)
a

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indeksowanie i wybór w NumPy

Utwórz macierz **mat** zgodnie z rezultatem poniżej:

```
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```



In [ ]:
a = np.arange(1, 26)
mat = np.copy(a.reshape(5,5))
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Napisz kod, który zwróci nastepujący fragment tablicy:

```
array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```


In [ ]:
mat[[1,3,4]]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Napisz kod, który zwróci nastepujący fragment tablicy:

```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```



In [ ]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Napisz kod, który zwróci nastepujący element tablicy:


```
20
```



In [ ]:
mat[3][4]


np.int64(20)

Napisz kod, który zwróci nastepujący fragment tablicy:

```
array([[ 2],
       [ 7],
       [12]])
```

In [ ]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

Napisz kod, który zwróci nastepujący fragment tablicy:

```
array([21, 22, 23, 24, 25])
```

In [ ]:
mat[4:]

array([[21, 22, 23, 24, 25]])

Napisz kod, który zwróci nastepujący fragment tablicy:

```
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Oblicz sumę wszystkich elementów w macierzy mat

In [ ]:
mat.sum()

np.int64(325)

#### Uzyskaj sumę dla poszczególnych kolumn w mat

In [ ]:
mat[[1]].sum()

np.int64(40)